language: java
jdk:
  -openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/respository'
    - '$HOME/.gradle'
script:  "./gradlew clean build"

notifications:
  email:
    recipients:
      - dotlamp@gmail.com
